print(30 < 20) #false
print(30 <= 20) #false
print(30 > 20) #true
print(30 >= 20) #true
print(30 == 20) #false
print(30 != 20) #true
print("mahadi" == "mahadi") #true
print("Mahadi" == "mahadi") #false
print("Mahadi" != "mahadi") #true
